# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QRCodeScan' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for QRCodeScan
   pod  'UMCShare/UI', '6.9.8'
   pod  'UMCShare/Social/ReducedQQ', '6.9.8'
   pod  'UMCShare/Social/ReducedWeChat', '6.9.8'
   pod  'AFNetworking', '~> 4.0'
   pod  'MBProgressHUD', '~> 1.1.0 '
   pod  'Masonry', '~> 1.1.0'
   pod  'MJRefresh', '~> 3.0'
   pod  'NoPayWeChatSDK' , '1.8.7.1'

   pod  'UMCAnalytics', '6.0.5'
   pod  'JPush', '3.2.6'
 
   pod  'ATAuthSDKMM', '1.0.4'
   pod  'BUAdSDKMM', '1.0.9'
   pod  'GDTMobSDKMM', '1.0.6'
   
  target 'QRCodeScanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QRCodeScanUITests' do
    # Pods for testing
  end

end
